# Generated by Django 5.0.3 on 2024-03-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='clock_in_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
