# Generated by Django 5.0.3 on 2024-03-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('consultant', 'Consultant'), ('Line Manager', 'Editor'), ('financeteam', 'Accounts Payable')], default='consultant', max_length=20),
        ),
    ]
